export const LOAN_RULES = {
  DELINQUENCY_DAYS: 30,
  LATE_FEE_PERCENTAGE: 0.03,

  TRANSACTION_TYPES: {
    DEPOSIT: "DEPOSITO",
    LOAN_PAYMENT: "PAGO_PRESTAMO",
  },

  OPERATION_TYPES: {
    DEPOSIT: "DEPOSITO",
    LOAN_PAYMENT: "PAGO_PRESTAMO",
  },

  MOVEMENT_TYPES: {
    CREDIT: "CREDITO",
    DEBIT: "DEBITO",
  },
};
